### ISSUE TITLE
Spotlight animation bugged

### ISSUE THREAD

**Issue by Waelahmed99** [MeitanteiAshour/SpotLightNavigationBar#1]
## Problem
Spotlight animation will not animate if **onItemPressed** property is null (not assigned)

## Suggested solutions
- [x] Try to perform another technique (Algorithm) to perform spotlight animation
- [x] Don't assume that **onItemPressed** is not null.

## Exception

> Exception caught by animation library 

The method 'call' was called on null.
Receiver: null
Tried calling: call(0)

**Comment by MahmoudAshours** [comment]
Solved the issue!
So , It has turned out that the onItemPressed should be @**required** .
Also the paint method get some issues and already fixed!
